-- ================================================================
-- MIGRATION: 005_rent.sql
-- Project:   Property Management Platform
-- Purpose:   Rent layer — schedules, charges, payments, allocations,
--            and arrears logging.
--
-- Run in:    Supabase Dashboard → SQL Editor
-- Run order: Must run AFTER 004_tenancies.sql
--
-- WHAT THIS FILE BUILDS:
--   1. rent_schedules        — recurring charge definitions per tenancy
--   2. charges               — individual payment demands (rent, fees, etc.)
--   3. payments              — money received from tenants
--   4. payment_allocations   — maps a payment to one or more charges
--   5. arrears_log           — point-in-time arrears snapshots
--   6. Triggers              — auto-sync org_id; auto-update charge status
--   7. Indexes               — fast lookups by org, tenancy, date, status
--   8. RLS policies          — org-scoped data isolation
--
-- DEPENDS ON:
--   001_foundation.sql  (organisations, profiles, roles, update_updated_at fn)
--   004_tenancies.sql   (tenancies — charges and payments reference tenancies.id)
--
-- KEY DESIGN DECISIONS:
--   - charges.paid_amount is a stored, denormalised value updated by a trigger
--     on payment_allocations. This avoids an expensive SUM() join on every
--     rent ledger query and keeps the status field consistent.
--   - charges.status is also managed by trigger: pending → overdue when
--     due_date passes (via the update_charge_status trigger). In production
--     this would be called by a nightly cron job. For now, status is set
--     correctly on insert based on the due_date at time of creation.
--   - payments are immutable records (no updated_at). Corrections are made
--     by voiding and re-entering, not editing. This preserves the audit trail.
--   - payment_allocations link a single payment to one or more charges. A
--     payment can partially cover a charge (partial payment), which is
--     reflected in charges.status = 'partial'.
--   - org_id is denormalised onto all tables for efficient RLS, synced via
--     trigger from tenancies.org_id.
-- ================================================================


-- ================================================================
-- SECTION 1: RENT SCHEDULES
--
-- A rent schedule defines a recurring financial obligation on a tenancy.
-- Each active schedule generates one charge row per billing period.
-- Schedules can be deactivated (end_date set or is_active = false)
-- when rent is renegotiated or the tenancy ends.
--
-- In practice, schedules would be activated by an admin and charges
-- generated by a scheduled function (e.g. on the 1st of each month).
-- For the MVP, charges are created manually via the UI.
-- ================================================================

CREATE TABLE rent_schedules (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID          NOT NULL REFERENCES organisations(id) ON DELETE RESTRICT,
  tenancy_id      UUID          NOT NULL REFERENCES tenancies(id) ON DELETE CASCADE,

  charge_type     TEXT          NOT NULL DEFAULT 'rent'
                                CHECK (charge_type IN (
                                  'rent', 'service_charge', 'utilities', 'parking', 'other'
                                )),
  description     TEXT,
  amount          NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  frequency       TEXT          NOT NULL DEFAULT 'monthly'
                                CHECK (frequency IN ('weekly', 'fortnightly', 'monthly', 'quarterly')),
  due_day         INT           NOT NULL DEFAULT 1
                                CHECK (due_day BETWEEN 1 AND 28),

  start_date      DATE          NOT NULL,
  end_date        DATE,

  is_active       BOOLEAN       NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_rent_schedules_updated_at
  BEFORE UPDATE ON rent_schedules
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ================================================================
-- SECTION 2: CHARGES
--
-- A charge is a single financial demand against a tenancy — one row
-- per expected payment. Charges are generated from a schedule
-- (schedule_id is set) or created ad-hoc (schedule_id = NULL).
--
-- CHARGE TYPES:
--   rent           — standard periodic rent payment
--   deposit        — tenancy deposit (one-off, on move-in)
--   late_fee       — late payment fee
--   service_charge — ongoing service charges (e.g. communal maintenance)
--   utilities      — utilities billed through the landlord
--   repair         — tenant-responsible repair costs recharged
--   other          — any other charge
--
-- STATUS LIFECYCLE:
--   pending → overdue  (when due_date passes with no payment)
--   pending → partial  (when some payment is allocated)
--   pending → paid     (when full amount is allocated)
--   overdue → partial  (late partial payment)
--   overdue → paid     (late full payment)
--   pending / overdue → waived   (charge written off)
--   pending / overdue → cancelled (charge removed before due)
--
-- paid_amount: stored denormalised value = SUM(payment_allocations.amount_allocated)
-- Updated by trigger on payment_allocations INSERT/UPDATE/DELETE.
-- ================================================================

CREATE TABLE charges (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID          NOT NULL REFERENCES organisations(id) ON DELETE RESTRICT,
  tenancy_id      UUID          NOT NULL REFERENCES tenancies(id) ON DELETE CASCADE,
  schedule_id     UUID          REFERENCES rent_schedules(id) ON DELETE SET NULL,

  charge_type     TEXT          NOT NULL DEFAULT 'rent'
                                CHECK (charge_type IN (
                                  'rent', 'deposit', 'late_fee', 'service_charge',
                                  'utilities', 'repair', 'other'
                                )),
  description     TEXT,
  due_date        DATE          NOT NULL,
  amount          NUMERIC(10,2) NOT NULL CHECK (amount > 0),

  paid_amount     NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),

  status          TEXT          NOT NULL DEFAULT 'pending'
                                CHECK (status IN (
                                  'pending', 'paid', 'partial', 'overdue', 'waived', 'cancelled'
                                )),

  notes           TEXT,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_charges_updated_at
  BEFORE UPDATE ON charges
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ================================================================
-- SECTION 3: PAYMENTS
--
-- A payment records money received from a tenant. One payment can
-- cover one or more charges (via payment_allocations). Payments are
-- immutable — do not edit a payment record; instead void the
-- allocation and create a corrected payment.
--
-- Payments are NOT directly linked to a charge. The link is made
-- via payment_allocations. A payment with no allocations is
-- effectively "unallocated" and sits as a credit until allocated.
-- ================================================================

CREATE TABLE payments (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID          NOT NULL REFERENCES organisations(id) ON DELETE RESTRICT,
  tenancy_id      UUID          NOT NULL REFERENCES tenancies(id) ON DELETE CASCADE,

  amount          NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  payment_date    DATE          NOT NULL,
  payment_method  TEXT          NOT NULL DEFAULT 'bank_transfer'
                                CHECK (payment_method IN (
                                  'bank_transfer', 'cash', 'cheque', 'card',
                                  'direct_debit', 'standing_order', 'other'
                                )),
  reference       TEXT,
  notes           TEXT,

  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
  -- Intentionally no updated_at — payments are immutable audit records
);


-- ================================================================
-- SECTION 4: PAYMENT ALLOCATIONS
--
-- Maps a payment to a specific charge. A payment can be split across
-- multiple charges (e.g. one bank transfer covers 2 months of rent).
-- A charge can receive allocations from multiple payments (partial
-- payments over time).
--
-- The UNIQUE constraint prevents double-allocating the same payment
-- to the same charge — instead update amount_allocated if needed.
-- ================================================================

CREATE TABLE payment_allocations (
  id               UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  payment_id       UUID          NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  charge_id        UUID          NOT NULL REFERENCES charges(id) ON DELETE RESTRICT,
  amount_allocated NUMERIC(10,2) NOT NULL CHECK (amount_allocated > 0),

  created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  UNIQUE (payment_id, charge_id)
);


-- ================================================================
-- SECTION 5: ARREARS LOG
--
-- Point-in-time snapshots of arrears per tenancy. Intended to be
-- populated by a nightly scheduled function. Enables trend charts
-- showing whether arrears are improving or worsening over time.
--
-- One row per tenancy per day. The UNIQUE constraint prevents
-- duplicate snapshots.
-- ================================================================

CREATE TABLE arrears_log (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID          NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  tenancy_id      UUID          NOT NULL REFERENCES tenancies(id) ON DELETE CASCADE,
  snapshot_date   DATE          NOT NULL,
  arrears_amount  NUMERIC(10,2) NOT NULL DEFAULT 0,

  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  UNIQUE (tenancy_id, snapshot_date)
);


-- ================================================================
-- SECTION 6: TRIGGERS
-- ================================================================

-- ---- 6a: Sync org_id from tenancy ----
-- Keeps charges.org_id, payments.org_id in sync with the parent
-- tenancy's org_id. Consistent pattern with previous migrations.

CREATE OR REPLACE FUNCTION sync_charge_org_id()
RETURNS TRIGGER AS $$
BEGIN
  SELECT org_id INTO NEW.org_id FROM tenancies WHERE id = NEW.tenancy_id;
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'Tenancy % not found or has no org_id', NEW.tenancy_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_charges_set_org_id
  BEFORE INSERT OR UPDATE OF tenancy_id ON charges
  FOR EACH ROW EXECUTE FUNCTION sync_charge_org_id();

CREATE TRIGGER trg_rent_schedules_set_org_id
  BEFORE INSERT OR UPDATE OF tenancy_id ON rent_schedules
  FOR EACH ROW EXECUTE FUNCTION sync_charge_org_id();

CREATE OR REPLACE FUNCTION sync_payment_org_id()
RETURNS TRIGGER AS $$
BEGIN
  SELECT org_id INTO NEW.org_id FROM tenancies WHERE id = NEW.tenancy_id;
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'Tenancy % not found or has no org_id', NEW.tenancy_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_payments_set_org_id
  BEFORE INSERT OR UPDATE OF tenancy_id ON payments
  FOR EACH ROW EXECUTE FUNCTION sync_payment_org_id();


-- ---- 6b: Update charges.paid_amount and status on allocation change ----
-- Called after any INSERT, UPDATE, or DELETE on payment_allocations.
-- Recomputes the total allocated amount and updates charges.status.

CREATE OR REPLACE FUNCTION refresh_charge_paid_amount()
RETURNS TRIGGER AS $$
DECLARE
  v_charge_id UUID;
  v_total     NUMERIC(10,2);
  v_amount    NUMERIC(10,2);
  v_due_date  DATE;
  v_new_status TEXT;
BEGIN
  -- Determine which charge to update
  IF TG_OP = 'DELETE' THEN
    v_charge_id := OLD.charge_id;
  ELSE
    v_charge_id := NEW.charge_id;
  END IF;

  -- Recompute total allocated
  SELECT COALESCE(SUM(amount_allocated), 0)
  INTO v_total
  FROM payment_allocations
  WHERE charge_id = v_charge_id;

  -- Get the charge amount and due_date
  SELECT amount, due_date INTO v_amount, v_due_date
  FROM charges
  WHERE id = v_charge_id;

  -- Determine new status
  IF v_total >= v_amount THEN
    v_new_status := 'paid';
  ELSIF v_total > 0 THEN
    v_new_status := 'partial';
  ELSIF v_due_date < CURRENT_DATE THEN
    v_new_status := 'overdue';
  ELSE
    v_new_status := 'pending';
  END IF;

  -- Update the charge
  UPDATE charges
  SET paid_amount = v_total,
      status      = v_new_status
  WHERE id = v_charge_id
    AND status NOT IN ('waived', 'cancelled');

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_payment_allocations_refresh_charge
  AFTER INSERT OR UPDATE OR DELETE ON payment_allocations
  FOR EACH ROW EXECUTE FUNCTION refresh_charge_paid_amount();


-- ================================================================
-- SECTION 7: INDEXES
-- ================================================================

-- rent_schedules
CREATE INDEX idx_rent_schedules_org_id       ON rent_schedules(org_id);
CREATE INDEX idx_rent_schedules_tenancy_id   ON rent_schedules(tenancy_id);
CREATE INDEX idx_rent_schedules_is_active    ON rent_schedules(is_active) WHERE is_active = true;

-- charges
CREATE INDEX idx_charges_org_id             ON charges(org_id);
CREATE INDEX idx_charges_tenancy_id         ON charges(tenancy_id);
CREATE INDEX idx_charges_due_date           ON charges(due_date);
CREATE INDEX idx_charges_status             ON charges(status);
CREATE INDEX idx_charges_org_month          ON charges(org_id, due_date);

-- payments
CREATE INDEX idx_payments_org_id            ON payments(org_id);
CREATE INDEX idx_payments_tenancy_id        ON payments(tenancy_id);
CREATE INDEX idx_payments_payment_date      ON payments(payment_date);

-- payment_allocations
CREATE INDEX idx_payment_allocations_payment_id ON payment_allocations(payment_id);
CREATE INDEX idx_payment_allocations_charge_id  ON payment_allocations(charge_id);

-- arrears_log
CREATE INDEX idx_arrears_log_org_id         ON arrears_log(org_id);
CREATE INDEX idx_arrears_log_tenancy_id     ON arrears_log(tenancy_id);
CREATE INDEX idx_arrears_log_snapshot_date  ON arrears_log(snapshot_date);


-- ================================================================
-- SECTION 8: ROW LEVEL SECURITY
-- ================================================================

-- ---- RENT SCHEDULES ----
ALTER TABLE rent_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view rent schedules"
  ON rent_schedules FOR SELECT
  TO authenticated
  USING (org_id IN (SELECT get_my_org_ids()));

CREATE POLICY "Admins can insert rent schedules"
  ON rent_schedules FOR INSERT
  TO authenticated
  WITH CHECK (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );

CREATE POLICY "Admins can update rent schedules"
  ON rent_schedules FOR UPDATE
  TO authenticated
  USING (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ---- CHARGES ----
ALTER TABLE charges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view charges"
  ON charges FOR SELECT
  TO authenticated
  USING (org_id IN (SELECT get_my_org_ids()));

CREATE POLICY "Admins can insert charges"
  ON charges FOR INSERT
  TO authenticated
  WITH CHECK (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );

CREATE POLICY "Admins can update charges"
  ON charges FOR UPDATE
  TO authenticated
  USING (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ---- PAYMENTS ----
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view payments"
  ON payments FOR SELECT
  TO authenticated
  USING (org_id IN (SELECT get_my_org_ids()));

CREATE POLICY "Admins can insert payments"
  ON payments FOR INSERT
  TO authenticated
  WITH CHECK (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ---- PAYMENT ALLOCATIONS ----
ALTER TABLE payment_allocations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view payment allocations"
  ON payment_allocations FOR SELECT
  TO authenticated
  USING (
    payment_id IN (
      SELECT id FROM payments
      WHERE org_id IN (SELECT get_my_org_ids())
    )
  );

CREATE POLICY "Admins can insert payment allocations"
  ON payment_allocations FOR INSERT
  TO authenticated
  WITH CHECK (
    payment_id IN (
      SELECT pa.id FROM payments pa
      JOIN profiles p ON p.org_id = pa.org_id
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );

CREATE POLICY "Admins can delete payment allocations"
  ON payment_allocations FOR DELETE
  TO authenticated
  USING (
    payment_id IN (
      SELECT pa.id FROM payments pa
      JOIN profiles p ON p.org_id = pa.org_id
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ---- ARREARS LOG ----
ALTER TABLE arrears_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view arrears log"
  ON arrears_log FOR SELECT
  TO authenticated
  USING (org_id IN (SELECT get_my_org_ids()));

CREATE POLICY "Admins can insert arrears log"
  ON arrears_log FOR INSERT
  TO authenticated
  WITH CHECK (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ================================================================
-- DONE ✓
--
-- Tables created:
--   rent_schedules       — recurring charge definitions per tenancy
--   charges              — individual payment demands
--   payments             — money received records (immutable)
--   payment_allocations  — payment → charge mapping
--   arrears_log          — point-in-time arrears snapshots
--
-- Functions created:
--   sync_charge_org_id()           — keeps charges/schedules org_id in sync
--   sync_payment_org_id()          — keeps payments org_id in sync
--   refresh_charge_paid_amount()   — updates paid_amount + status on allocation change
--
-- NEXT MIGRATION: 006_maintenance.sql
--   → issues, work_orders, work_order_notes, vendors
--
-- HOW TO VERIFY:
--   Supabase → Table Editor: check all 5 tables exist.
--   Insert a charge, then insert a payment_allocation for it:
--   → charges.paid_amount should update automatically.
--   → charges.status should change from 'pending' to 'paid'.
-- ================================================================
