-- ================================================================
-- MIGRATION: 011_reporting.sql
-- Project:   Property Management Platform
-- Purpose:   Reporting layer — point-in-time snapshots for the
--            portfolio dashboard KPIs and historical charting.
--
-- Run in:    Supabase Dashboard → SQL Editor
-- Run order: Must run AFTER 010_notifications.sql
--
-- WHAT THIS FILE BUILDS:
--   1. occupancy_snapshots    — daily occupancy rate per org
--   2. financial_snapshots    — monthly rent collected vs due per org
--   3. property_valuations    — on-demand property value estimates
--   4. Indexes                — fast lookups by org and date for charts
--   5. RLS policies           — owners, managers, accountants can read;
--                               only service_role can write snapshots
--
-- DEPENDS ON:
--   001_foundation.sql  (organisations, profiles, roles)
--   002_properties.sql  (properties — valuations reference property)
--
-- KEY DESIGN DECISIONS:
--   - Snapshot tables are write-once records of state at a point in time.
--     They do NOT attempt to reconstruct history — they ARE the history.
--     A nightly Edge Function (cron) inserts one row per org per day/month.
--   - occupancy_snapshots uses a UNIQUE(org_id, snapshot_date) constraint
--     so the nightly job can use INSERT ... ON CONFLICT DO UPDATE to be
--     idempotent (safe to re-run without duplicating data).
--   - financial_snapshots.snapshot_month is stored as the FIRST DAY of the
--     month (YYYY-MM-01) so queries like WHERE snapshot_month >= '2024-01-01'
--     work naturally with date arithmetic.
--   - property_valuations are on-demand — entered manually by the owner or
--     via an estate agent integration. Not generated by a cron job.
--     They are used to compute net yield and portfolio value on the dashboard.
--   - All snapshot tables use ON DELETE CASCADE from organisations so a
--     deleted org cleans up all its history automatically.
--   - property_valuations uses ON DELETE CASCADE from properties so deleting
--     a property removes its valuation history (expected behaviour for a
--     hard delete — data cannot be recovered without a backup restore).
-- ================================================================


-- ================================================================
-- SECTION 1: OCCUPANCY SNAPSHOTS
--
-- A daily snapshot of unit occupancy state across the org.
-- Drives the occupancy rate trend chart on the portfolio dashboard.
-- ================================================================

CREATE TABLE occupancy_snapshots (
  id                UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id            UUID        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  snapshot_date     DATE        NOT NULL,

  total_units       INT         NOT NULL DEFAULT 0 CHECK (total_units >= 0),
  occupied_units    INT         NOT NULL DEFAULT 0 CHECK (occupied_units >= 0),
  vacant_units      INT         NOT NULL DEFAULT 0 CHECK (vacant_units >= 0),
  maintenance_units INT         NOT NULL DEFAULT 0 CHECK (maintenance_units >= 0),

  -- Computed at snapshot time (stored to avoid recomputing on read)
  occupancy_rate    NUMERIC(5,2) CHECK (occupancy_rate BETWEEN 0 AND 100),

  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (org_id, snapshot_date)
);


-- ================================================================
-- SECTION 2: FINANCIAL SNAPSHOTS
--
-- A monthly summary of rent due vs collected for the org.
-- Drives the rent collection trend chart on the portfolio dashboard.
-- ================================================================

CREATE TABLE financial_snapshots (
  id                  UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id              UUID        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  snapshot_month      DATE        NOT NULL,  -- always the 1st of the month, e.g. 2024-06-01

  gross_rent_due      NUMERIC(12,2) NOT NULL DEFAULT 0,   -- sum of charges due this month
  rent_collected      NUMERIC(12,2) NOT NULL DEFAULT 0,   -- sum of payments received
  arrears_total       NUMERIC(12,2) NOT NULL DEFAULT 0,   -- running arrears balance
  maintenance_spend   NUMERIC(12,2) NOT NULL DEFAULT 0,   -- sum of work_orders.final_amount
  mortgage_total      NUMERIC(12,2) NOT NULL DEFAULT 0,   -- sum of units.mortgage_monthly

  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (org_id, snapshot_month)
);


-- ================================================================
-- SECTION 3: PROPERTY VALUATIONS
--
-- Manual or third-party valuation records for individual properties.
-- Supports multiple valuations per property (valuation history).
-- The most recent valuation is used for net yield and portfolio value
-- calculations on the dashboard (replaces the current_valuation column
-- on properties for the purposes of history tracking).
-- ================================================================

CREATE TABLE property_valuations (
  id                UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id            UUID        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  property_id       UUID        NOT NULL REFERENCES properties(id) ON DELETE CASCADE,

  valuation_date    DATE        NOT NULL,
  valuation_amount  NUMERIC(12,2) NOT NULL CHECK (valuation_amount > 0),

  valuation_source  TEXT        NOT NULL DEFAULT 'manual'
                                CHECK (valuation_source IN (
                                  'manual',         -- entered by owner
                                  'estate_agent',   -- formal estate agent appraisal
                                  'surveyor',       -- RICS surveyor report
                                  'mortgage',       -- lender valuation for remortgage
                                  'automated'       -- future: Zoopla/Rightmove AVM
                                )),

  notes             TEXT,
  valuer_name       TEXT,       -- name of estate agent or surveyor, if applicable

  created_by        UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
  -- No updated_at — valuations are immutable records. Correct by adding a new row.
);


-- ================================================================
-- SECTION 4: INDEXES
-- ================================================================

-- occupancy_snapshots
CREATE INDEX idx_occupancy_snapshots_org_id        ON occupancy_snapshots(org_id);
CREATE INDEX idx_occupancy_snapshots_date          ON occupancy_snapshots(snapshot_date DESC);
CREATE INDEX idx_occupancy_snapshots_org_date      ON occupancy_snapshots(org_id, snapshot_date DESC);

-- financial_snapshots
CREATE INDEX idx_financial_snapshots_org_id        ON financial_snapshots(org_id);
CREATE INDEX idx_financial_snapshots_month         ON financial_snapshots(snapshot_month DESC);
CREATE INDEX idx_financial_snapshots_org_month     ON financial_snapshots(org_id, snapshot_month DESC);

-- property_valuations
CREATE INDEX idx_property_valuations_org_id        ON property_valuations(org_id);
CREATE INDEX idx_property_valuations_property_id   ON property_valuations(property_id);
CREATE INDEX idx_property_valuations_date          ON property_valuations(valuation_date DESC);
CREATE INDEX idx_property_valuations_property_date ON property_valuations(property_id, valuation_date DESC);


-- ================================================================
-- SECTION 5: ROW LEVEL SECURITY
--
-- Snapshot tables are read-only for authenticated users.
-- All inserts are performed by server-side code (service_role),
-- so no INSERT policy is needed for the authenticated role.
--
-- occupancy_snapshots & financial_snapshots:
--   - Owners, managers, and accountants can read.
--   - No write access via authenticated role.
--
-- property_valuations:
--   - Org members can view (useful for staff checking portfolio value).
--   - Owners and managers can create new valuation records.
--   - Owners can delete valuation records (e.g. entered in error).
-- ================================================================

-- ---- OCCUPANCY SNAPSHOTS ----
ALTER TABLE occupancy_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners managers accountants can view occupancy snapshots"
  ON occupancy_snapshots FOR SELECT
  TO authenticated
  USING (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ---- FINANCIAL SNAPSHOTS ----
ALTER TABLE financial_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners managers accountants can view financial snapshots"
  ON financial_snapshots FOR SELECT
  TO authenticated
  USING (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager', 'accountant')
    )
  );


-- ---- PROPERTY VALUATIONS ----
ALTER TABLE property_valuations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members can view property valuations"
  ON property_valuations FOR SELECT
  TO authenticated
  USING (org_id IN (SELECT get_my_org_ids()));

CREATE POLICY "Owners and managers can add valuations"
  ON property_valuations FOR INSERT
  TO authenticated
  WITH CHECK (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name IN ('owner', 'manager')
    )
  );

CREATE POLICY "Owners can delete valuations"
  ON property_valuations FOR DELETE
  TO authenticated
  USING (
    org_id IN (
      SELECT p.org_id FROM profiles p
      JOIN roles r ON r.id = p.role_id
      WHERE p.user_id = auth.uid()
        AND p.is_active = true
        AND r.name = 'owner'
    )
  );


-- ================================================================
-- DONE ✓
--
-- Tables created:
--   occupancy_snapshots   — daily org-level occupancy rates
--   financial_snapshots   — monthly org-level rent collection summary
--   property_valuations   — on-demand property valuation history
--
-- Edge Functions to wire up later:
--   - nightly-snapshot: compute and upsert occupancy_snapshot
--     + financial_snapshot for every active org
--   Run via Supabase cron: '0 2 * * *' (2am UTC daily)
--
-- NEXT MIGRATION: 012_delete_property.sql
--   → SECURITY DEFINER cascade delete function
-- ================================================================
